### PR TITLE
feat: add query of DataValidationCertificatesByRound

### PR DESCRIPTION
**Pull request by hansol-medi**
Implemented query of `DataValidationCertificatesByRound`, which returns all the certs by pool and round.

I would suggest to change the name of `DataValidationCertificate` to `DataCertificate` because it's too long to name other functions. What do you think?

### CODE REVIEW

**Comment by hansol-medi** [comment]
I'm going to add pagination in this query.

**Review by youngjoon-lee — APPROVED** [review]
I agree to shorten the name to `DataCertificate` or `DataCert`.

**Review by inchori — APPROVED** [review]
LGTM 👍

**Review by gyuguen — APPROVED** [review]
LGTM 👍

**Comment by gyuguen** [comment]
I also agree to the short name change.

**Comment by hansol-medi** [comment]
> I agree to shorten the name to DataCertificate or DataCert.

Good. I will rename it in the next PR.

**Pull request merged**
