### PR TITLE
feat: add OracleUpgradeInfo to genesis

### PR DESCRIPTION
**Pull request by gyuguen**
Implement to import and export OracleUpgradeInfo in genesis

### CODE REVIEW

**Review by H4NLee — COMMENTED** [review]
Let's do validate genesis state of upgrade info in `types/genesis.go` :)

**Comment by gyuguen** [comment]
> Let's do validate genesis state of upgrade info in `types/genesis.go` :)

Thank you! I added it(https://github.com/medibloc/panacea-core/pull/457/commits/a2eccf4add68536c1318af1db3762e0f5224cf63)

**Review by H4NLee — APPROVED** [review]
lgtm

**Review by audtlr24 — APPROVED** [review]
LGTM! 👍

**Review by inchori — APPROVED** [review]
LGTM

**Pull request merged**
