### PR TITLE
feat: Remove unnecessary gogoproto.jsontag in the `did.proto`

### LINKED ISSUE #176: Make DIDDocument returned with camelCase (for W3C specs)
All protobuf field names are snake_case as Google recommended.
However, we want for DID documents to be returned with camelCase in order to obey the W3C specs.

Fortunately, our implementation can read camelCase DID documents, because we've added `json_name` tags in the `did.proto`.
But, it seems it doesn't work well when returning DID documents to users.
```json
{
  "did_document_with_seq": {
    "document": {
      "contexts": [
        "https://www.w3.org/ns/did/v1"
      ],
      "id": "did:panacea:4Fsrryj58HP3zxRE9FPBcsG4EehAmoSuGXuvvpxbrziF",
      "controller": null,
      "verification_methods": [
        {
          "id": "did:panacea:4Fsrryj58HP3zxRE9FPBcsG4EehAmoSuGXuvvpxbrziF#key1",
          "type": "Secp256k1VerificationKey2018",
          "controller": "did:panacea:4Fsrryj58HP3zxRE9FPBcsG4EehAmoSuGXuvvpxbrziF",
          "public_key_base58": "ecfi6w7BeaWmumQ1s7nHvcMasAWhpPkXNoPZ3eXyERLU"
        }
      ],
      "authentications": [
        "did:panacea:4Fsrryj58HP3zxRE9FPBcsG4EehAmoSuGXuvvpxbrziF#key1"
      ],
      "assertion_methods": [
      ],
      "key_agreements": [
      ],
      "capability_invocations": [
      ],
      "capability_delegations": [
      ],
      "services": [
      ]
    },
    "sequence": "0"
  }
}
```

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Closes #176 

We decided to not make our JSON response as the W3C JSON-LD format: https://github.com/medibloc/panacea-core/issues/176#issuecomment-876294047.
But, I just refined the `did.proto` by removing some unnecessary tags.

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
👍 
Thank you. As long as the CI passes, it can be merged!

**Comment by youngjoon-lee** [comment]
@gyuguen 
4ead621 I fixed tests by using `jsonpb.Unmarshal` to read JSON files in the CLI. The `json.Unmarshal` expected snake_case because I removed `(gogoproto.jsontag)`.

Let's think that the rule of thumb is using `jsonpb.Unmarshal` for unmarshal `proto.Message`s, regardless of the field names and custome type definitions. That's also what Google recommended.

**Comment by gyuguen** [comment]
> I fixed tests by using `jsonpb.Unmarshal` to read JSON files in the CLI. The `json.Unmarshal` expected snake_case because I removed `(gogoproto.jsontag)`. Also, it doesn't handle custom types.

I'm checked. 
Test passed well, so we can merge it. :)

**Review by gyuguen — APPROVED** [review]
👍

**Pull request merged**
