### PR TITLE
feat: add distribution of oracle rewards for data verification

### PR DESCRIPTION
**Pull request by H4NLee**
Based on #469 
Added oracle rewards distribution for data verification. Tests have been modified accordingly.

For simplicity, 50% of oracle commission is distributed to oracles who cast valid vote.
The rest of commission (rest of 50%) will be distributed when data delivery vote is passed.

### CODE REVIEW

**Review by audtlr24 — APPROVED** [review]
LGTM! 👍 
`distributeOracleRewards` in `DataDelivery` is applied in the next PR, right?

And, there is one thing I would like to ask for your opinion. How about defining `NewDecWithPrec(5, 1)` for 50% of oracle rewards as a const value. It can be used in `DataDelivery` oracle rewards.

**Comment by H4NLee** [comment]
> `distributeOracleRewards` in DataDelivery is applied in the next PR, right?

Yes. `distributeOracleRewards` will also be used to distribute rewards for data delivery and it will be implemented in the next PR. 

> And, there is one thing I would like to ask for your opinion. How about defining NewDecWithPrec(5, 1) for 50% of oracle rewards as a const value. It can be used in DataDelivery oracle rewards.

Ok. it is done in [eb001cb](https://github.com/medibloc/panacea-core/pull/473/commits/eb001cb4a3358ce61d83e71cebfa8e8a796389ee)

**Review by gyuguen — APPROVED** [review]
LGTM

**Review by youngjoon-lee — COMMENTED** [review]
lgtm. danke

**Pull request merged**
