### PR TITLE
feat: add `CreateDeal`, query a `Deal` CLI

### PR DESCRIPTION
**Pull request by inchori**
Add a CLI of `CreateDeal` Tx and query a `Deal`.

### CODE REVIEW

**Review by audtlr24 — APPROVED** [review]
Thanks, I think we need `GetDeals()` cmd as well.

**Comment by inchori** [comment]
@audtlr24 Thanks! I add a `GetDeals()` CLI in #532.

**Review by youngjoon-lee — APPROVED** [review]
good

**Review by H4NLee — APPROVED** [review]
lgtm

**Pull request merged**
