### PR TITLE
build: [v2.0.x] use the official v0.9.3 release of cosmos/ledger-go

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Based on the PR #466 

Please find the detailed history from https://github.com/medibloc/panacea-core/pull/367. Unfortunately, the `cosmos/ledger-go@v0.9.3` hasn't been applied to the `cosmos/cosmos-sdk` yet.

### CODE REVIEW

**Review by H4NLee — APPROVED** [review]
LGTM

**Review by audtlr24 — APPROVED** [review]
LGTM

**Review by inchori — APPROVED** [review]
LGTM 👍

**Review by gyuguen — COMMENTED** [review]
LGTM

**Review by gyuguen — APPROVED** [review]

**Pull request merged**
