### PR TITLE
docs: fix roadmap: whitepaper revision schedule

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Previously, the whitepaper revision was in both 2022 Q3 and 2023 Q3. I deleted the one in 2023 Q3.

### CODE REVIEW

**Review by hansol-medi — APPROVED** [review]
T_T we all missed. sorry about that

**Review by tjyoon0324 — APPROVED** [review]
Fine with me! Thanks Youngjoon!

**Review by inchori — APPROVED** [review]
Thanks!! 👍

**Review by gyuguen — APPROVED** [review]
LGTM 👍

**Comment by youngjoon-lee** [comment]
> T_T we all missed. sorry about that

No problem. I also thought we will probably revise the whitepaper more than twice in the future. But, I think it would be better to mention it only once in the roadmap.

**Pull request merged**
