### PR TITLE
feat: use medibloc/cosmos-sdk for `min_commission_rate` + add upgrade handler

### LINKED ISSUE #290: Have minimum commission rate
For healthier validator/delegator ecosystem, we can try to introduce the minimum commission rate.

- Cosmos SDK `x/staking` module must have a `min_commssion_rate` param.
  - Osmosis has already done this work by forking https://github.com/cosmos/cosmos-sdk as https://github.com/osmosis-labs/cosmos-sdk.
  - Similarly, I've already done it as https://github.com/medibloc/cosmos-sdk/pull/27
- panacea-core should have an upgrade handler which updates validator commissions that is smaller than `min_commission_rate`.
  - References
    - https://github.com/osmosis-labs/osmosis/pull/184
    - https://github.com/osmosis-labs/osmosis/pull/353
- Write a signaling proposal for setting `min_commission_rate` to 3% initially as Hojin suggested. She said that 5% may be considered too dramatic because we already started without any limitation.
  - Share this proposal to participants and open a on-chain governance after semi-consensus is made with participants.

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Closes #290

### Important
This PR is based on the `v2.0` branch which currently points to the tag `v2.0.2`. If this feature is decided to be deployed to mainnet, we must cherry-pick this PR to the `master` branch as well.

### Changes

- Used medibloc/cosmos-sdk: https://github.com/medibloc/cosmos-sdk/pull/27
   - You don't need to review `*.proto` and `swagger.json` which is regenerated by `make proto-update-dep` and `make proto-swagger-gen`.
- Implemented an upgrade handler which does:
  - Set the new `min-commission-rate` genesis parameter to 3%.
  - Update the commission rate of validators whose commission rate is smaller than the `min-commission-rate` 3%.

### Tests
It was hard to automate tests. I tested the upgrade progress manually.

### TODO
https://github.com/medibloc/panacea-core/pull/291/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R59
https://github.com/medibloc/panacea-core/pull/291/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R37

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
LGTM 👍

**Comment by gyuguen** [comment]
We will have to edit CHANGELOG.md later too.

**Review by hansol-medi — APPROVED** [review]
LGTM

**Comment by youngjoon-lee** [comment]
@gyuguen @hansol-medi 
https://github.com/medibloc/panacea-core/pull/291/commits/29373c3d25a1a35e3821c15d758d5bf04f5cd852
I just pushed the last commit which uses the properly released version of medibloc/cosmos-sdk.

**Pull request merged**
